version: '2'
services:
    ror:
        build: ror/.
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - ./ror:/ror
        #    - ./ror/app:/apollo/app
        ports:
            - "3000:3000"
        restart: always
    node:
        build: node/.
        command: node server.js
        #depends_on: 
        links:
            - ror
            - redis
        volumes:
            - ./node/server.js:/node/server.js
            - ./node/common.js:/node/common.js
        restart: always
    http:
        build: http/.
        command: http-server . -p 80
        depends_on: 
            - ror
        ports:
            - "8001:80"
        volumes:
            - ./http/js:/http/js
            - ./http/css:/http/css
            - ./http/partials:/http/partials
            - ./http/favicon.ico:/http/favicon.ico
            - ./http/index.html:/http/index.html
        restart: always
    redis:
        image: redis
        ports:
            - "6379:6379"
        restart: always
